---
- name: copy the node_exporter systemd service file
  ansible.builtin.template:
    src: "node_exporter.service.j2"
    dest: "/etc/systemd/system/node_exporter.service"
    owner: root
    group: root
    mode: 0644
  notify: restart node_exporter

- name: create node_exporter config directory
  ansible.builtin.file:
    path: "/etc/node_exporter"
    state: directory
    owner: root
    group: root
    mode: u+rwX,g+rwX,o=rX

- name: copy the node_exporter config file
  ansible.builtin.template:
    src: "config.yaml.j2"
    dest: "/etc/node_exporter/config.yaml"
    owner: root
    group: root
    mode: 0644
  notify: restart node_exporter

- name: create textfile collector directory
  ansible.builtin.file:
    path: "{{ node_exporter_textfile_dir }}"
    state: directory
    owner: "{{ node_exporter_system_user }}"
    group: "{{ node_exporter_system_group }}"
    mode: u+rwX,g+rwX,o=rX
  when: node_exporter_textfile_dir | length > 0
