---
- name: Install required packages
  apt:
    name:
      - ca-certificates
      - curl
    state: present
  become: yes

- name: Create keyring directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: yes

- name: Download and add Docker's GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
  become: yes

- name: Set permissions for GPG key
  file:
    path: /etc/apt/keyrings/docker.asc
    mode: '0644'
  become: yes

- name: Add Docker repository to Apt sources
  lineinfile:
    path: /etc/apt/sources.list.d/docker.list
    create: yes
    line: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
  become: yes

- name: Update package list
  apt:
    update_cache: yes
  become: yes

- name: Install Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  become: yes
  register: docker_installation

- name: Check if Docker installation was successful
  debug:
    msg: "Docker installation successful"
  when: docker_installation.changed
  notify: Enable and start Docker service
